
import { GoogleGenAI } from "@google/genai";

// TODO: Replace with your actual API key handling.
// For this project, we assume process.env.API_KEY is available.
const API_KEY = process.env.API_KEY;

if (!API_KEY) {
  // In a real app, you would handle this more gracefully.
  // For this project, we'll proceed assuming it's set in the environment.
  console.warn("API_KEY is not set. Image generation will fail.");
}

const ai = new GoogleGenAI({ apiKey: API_KEY! });

export interface GenerationConfig {
  prompt: string;
  aspectRatio: "1:1" | "3:4" | "4:3" | "9:16" | "16:9";
  negativePrompt?: string; // This is a UI feature, Imagen API doesn't have a direct negative prompt param
}

/**
 * Generates an image using the Imagen 2 model.
 * @param config The configuration for image generation.
 * @returns A base64 encoded image string.
 */
export const generateImage = async (config: GenerationConfig): Promise<string> => {
  // TODO: Integrate real AI API here.
  // The following is the actual integration for Imagen-4.0
  try {
    const response = await ai.models.generateImages({
        model: 'imagen-4.0-generate-001',
        prompt: config.prompt,
        config: {
          numberOfImages: 1,
          outputMimeType: 'image/png', // Using PNG for better quality
          aspectRatio: config.aspectRatio,
        },
    });

    if (response.generatedImages && response.generatedImages.length > 0) {
      const base64ImageBytes: string = response.generatedImages[0].image.imageBytes;
      return `data:image/png;base64,${base64ImageBytes}`;
    } else {
      throw new Error("No image was generated by the API.");
    }
  } catch (error) {
    console.error("Error generating image with Gemini API:", error);
    // As a fallback, you could return a placeholder or throw the error
    // For a better UX, we'll throw a more user-friendly error message.
    throw new Error("Failed to generate image. Please check your prompt or API key and try again.");
  }
};
